# Usage:python3 smGenerator.py path/to/song.mp3

# Arrow columns:  0=Left  1=Down  2=Up  3=Right

import os
import sys
import numpy as np
import torch
import librosa

from timingGrid import TimingGrid
from lstmModel import StepLSTM
from trainModel import load_model

# One threshold per difficulty
THRESHOLDS = {
    "Beginner":  0.55,
    "Easy":      0.50,
    "Medium":    0.45,
    "Hard":      0.38,
    "Challenge": 0.30,
}

# StepMania numeric difficulty ratings
DIFFICULTY_RATINGS = {
    "Beginner":  1,
    "Easy":      3,
    "Medium":    5,
    "Hard":      7,
    "Challenge": 9,
}

SUBDIVISIONS_PER_MEASURE = 16


def predict_arrows(model: StepLSTM, grid: list, seq_len: int = 64) -> np.ndarray:
    n = len(grid)
    features = np.stack([cell["features"] for cell in grid])

    prob_sum   = np.zeros((n, 4), dtype=np.float32)
    prob_count = np.zeros((n, 1), dtype=np.float32)

    stride = seq_len // 2

    model.eval()
    with torch.no_grad():
        for start in range(0, n, stride):
            end    = min(start + seq_len, n)
            window = features[start:end]

            if len(window) < seq_len:
                pad    = np.zeros((seq_len - len(window), window.shape[1]), dtype=np.float32)
                window = np.vstack([window, pad])

            x    = torch.from_numpy(window).unsqueeze(0)
            pred = model(x).squeeze(0).numpy()

            actual_len = end - start
            prob_sum[start:end]   += pred[:actual_len]
            prob_count[start:end] += 1

    # Average overlapping predictions
    probs = prob_sum / np.maximum(prob_count, 1)
    return probs


def probs_to_arrows(probs: np.ndarray, threshold: float) -> np.ndarray:
    arrows = (probs >= threshold).astype(np.float32)

    for col in range(4):
        col_arr = arrows[:, col]
        last_on = -2
        for i in range(len(col_arr)):
            if col_arr[i] == 1.0:
                if i - last_on < 2:
                    arrows[i, col] = 0.0
                else:
                    last_on = i

    return arrows


def format_measure(arrows_in_measure: np.ndarray) -> str:
    rows = []
    for row in arrows_in_measure:
        rows.append("".join("1" if v > 0.5 else "0" for v in row))
    return "\n".join(rows)

def build_sm_content(
    song_name: str,
    audio_filename: str,
    tempo: float,
    offset: float,
    all_arrows: dict,
) -> str:
    """
    Assembles the full text content of a .sm file.
    all_arrows is a dict mapping difficulty name -> (N, 4) binary array.
    """
    lines = []

    #Global metadata
    lines += [
        f"#TITLE:{song_name};",
        f"#SUBTITLE:;",
        f"#ARTIST:Unknown;",
        f"#TITLETRANSLIT:;",
        f"#SUBTITLETRANSLIT:;",
        f"#ARTISTTRANSLIT:;",
        f"#GENRE:;",
        f"#CREDIT:Auto-generated by smGenerator.py;",
        f"#BANNER:;",
        f"#BACKGROUND:;",
        f"#LYRICSPATH:;",
        f"#CDTITLE:;",
        f"#MUSIC:{audio_filename};",
        f"#OFFSET:{offset:.3f};",
        f"#SAMPLESTART:0.000;",
        f"#SAMPLELENGTH:10.000;",
        f"#SELECTABLE:YES;",
        f"#BPMS:0.000={tempo:.3f};",
        f"#STOPS:;",
        "",
    ]

    for diff, arrows in all_arrows.items():
        n         = len(arrows)
        rating    = DIFFICULTY_RATINGS.get(diff, 5)

        remainder = n % SUBDIVISIONS_PER_MEASURE
        if remainder != 0:
            pad    = np.zeros((SUBDIVISIONS_PER_MEASURE - remainder, 4), dtype=np.float32)
            arrows = np.vstack([arrows, pad])

        n_measures = len(arrows) // SUBDIVISIONS_PER_MEASURE

        lines += [
            "#NOTES:",
            "     dance-single:",
            "     :",
            f"     {diff}:",
            f"     {rating}:",
            "     0.000,0.000,0.000,0.000,0.000:",
        ]

        for m in range(n_measures):
            chunk        = arrows[m * SUBDIVISIONS_PER_MEASURE : (m + 1) * SUBDIVISIONS_PER_MEASURE]
            measure_str  = format_measure(chunk)
            separator    = ";" if m == n_measures - 1 else ","
            lines.append(measure_str)
            lines.append(separator)

        lines.append("")

    return "\n".join(lines)


def generate_sm(
    audio_path: str,
    model: StepLSTM,
    output_dir: str = ".",
    difficulties: list = None,
) -> str:
    if difficulties is None:
        difficulties = list(THRESHOLDS.keys())

    print(f"\n[smGenerator] Loading audio: {audio_path}")
    audio_data, sr = librosa.load(audio_path, sr=None, mono=True)

    onset_env          = librosa.onset.onset_strength(y=audio_data, sr=sr)
    tempo, beat_frames = librosa.beat.beat_track(y=audio_data, sr=sr, onset_envelope=onset_env)
    beat_times         = librosa.frames_to_time(beat_frames, sr=sr)
    tempo_val          = float(np.atleast_1d(tempo)[0])
    duration           = librosa.get_duration(y=audio_data, sr=sr)
    offset             = float(beat_times[0]) if len(beat_times) > 0 else 0.0

    print(f"[smGenerator] BPM={tempo_val:.1f}  Duration={duration:.1f}s  Offset={offset:.3f}s")

    grid  = TimingGrid(audio_data, sr, tempo_val, beat_times).build_grid()
    probs = predict_arrows(model, grid)
    print(f"[smGenerator] Grid positions: {len(grid)}")

    all_arrows = {}
    for diff in difficulties:
        threshold         = THRESHOLDS[diff]
        arrows            = probs_to_arrows(probs, threshold)
        density           = arrows.any(axis=1).mean()
        all_arrows[diff]  = arrows
        print(f"[smGenerator] {diff:10s}  threshold={threshold}  step_density={density:.2f}")

    song_name      = os.path.splitext(os.path.basename(audio_path))[0]
    audio_filename = os.path.basename(audio_path)
    sm_content     = build_sm_content(song_name, audio_filename, tempo_val, offset, all_arrows)

    os.makedirs(output_dir, exist_ok=True)
    out_path = os.path.join(output_dir, f"{song_name}.sm")
    with open(out_path, "w") as f:
        f.write(sm_content)

    print(f"[smGenerator] Saved → {out_path}")
    return out_path


if __name__ == "__main__":
    if len(sys.argv) > 1:
        audio_file = sys.argv[1]
    else:
        import tkinter as tk
        from tkinter import filedialog
        root = tk.Tk()
        root.withdraw()
        audio_file = filedialog.askopenfilename(
            title="Select audio file",
            filetypes=[("Audio Files", "*.mp3 *.wav *.ogg *.flac"), ("All Files", "*.*")],
        )
        root.destroy()

    if not audio_file:
        print("No file selected.")
        sys.exit(1)

    model    = load_model()
    out_path = generate_sm(audio_file, model, output_dir="./output")
    print(f"\nDone! StepMania file saved to: {out_path}")